version: '3.9'

services:
  node-server:
    build: './web'
    container_name: 'node-server'
    ports:
      - '3000:3000'
  nginx-proxy:
    build: './proxy'
    container_name: 'nginx-proxy'
    links:
      - 'node-server:server'
    ports:
      - '443:443'

